export const woodPlanks = [
    // [Name, Suffix]
    ['oak', 'planks'],
    ['spruce', 'planks'],
    ['birch', 'planks'],
    ['jungle', 'planks'],
    ['acacia', 'planks'],
    ['dark_oak', 'planks'],
    ['mangrove', 'planks'],
    ['cherry', 'planks'],
    ['bamboo', 'planks'],
    ['bamboo_mosaic', ''],
    ['crimson', 'planks'],
    ['warped', 'planks'],
];

export const isomorphisms = [
    // Wood stonecutter isomorphisms.
    ['oak_planks', 'oak_stairs'],
    ['spruce_planks', 'spruce_stairs'],
    ['birch_planks', 'birch_stairs'],
    ['jungle_planks', 'jungle_stairs'],
    ['acacia_planks', 'acacia_stairs'],
    ['dark_oak_planks', 'dark_oak_stairs'],
    ['mangrove_planks', 'mangrove_stairs'],
    ['cherry_planks', 'cherry_stairs'],
    ['bamboo_planks', 'bamboo_stairs'],
    ['bamboo_mosaic', 'bamboo_mosaic_stairs'],
    ['crimson_planks', 'crimson_stairs'],
    ['warped_planks', 'warped_stairs'],

    // Other stonecutter isomorphisms.
    ['stone', 'stone_stairs', 'stone_bricks', 'stone_brick_stairs', 'stone_brick_wall', 'chiseled_stone_bricks'],
    ['cobblestone', 'cobblestone_stairs', 'cobblestone_wall'],
    ['mossy_cobblestone', 'mossy_cobblestone_stairs', 'mossy_cobblestone_wall'],
    ['mossy_stone_bricks', 'mossy_stone_brick_stairs', 'mossy_stone_brick_wall'],
    ['granite', 'granite_stairs', 'polished_granite', 'polished_granite_stairs', 'granite_wall'],
    ['diorite', 'diorite_stairs', 'polished_diorite', 'polished_diorite_stairs', 'diorite_wall'],
    ['andesite', 'andesite_stairs', 'polished_andesite', 'polished_andesite_stairs', 'andesite_wall'],
    ['cobbled_deepslate', 'deepslate_brick_stairs', 'cobbled_deepslate_wall', 'cobbled_deepslate_stairs', 'polished_deepslate_stairs', 'deepslate_brick_wall', 'deepslate_tile_stairs', 'deepslate_bricks', 'chiseled_deepslate', 'polished_deepslate', 'deepslate_tile_wall', 'deepslate_tiles', 'polished_deepslate_wall'],
    ['bricks', 'brick_stairs', 'brick_wall'],
    ['mud_bricks', 'mud_brick_stairs', 'mud_brick_wall', 'packed_mud'],
    ['sandstone', 'cut_sandstone', 'sandstone_stairs', 'sandstone_wall', 'chiseled_sandstone'],
    ['smooth_sandstone', 'smooth_sandstone_stairs'],
    ['red_sandstone', 'cut_red_sandstone', 'red_sandstone_stairs', 'red_sandstone_wall', 'chiseled_red_sandstone'],
    ['smooth_red_sandstone', 'smooth_red_sandstone_stairs'],
    ['prismarine', 'prismarine_stairs', 'prismarine_wall'],
    ['prismarine_bricks', 'prismarine_brick_stairs'],
    ['dark_prismarine', 'dark_prismarine_stairs'],
    ['nether_bricks', 'nether_brick_stairs', 'nether_brick_wall', 'chiseled_nether_bricks'],
    ['red_nether_bricks', 'red_nether_brick_stairs', 'red_nether_brick_wall'],
    ['blackstone', 'blackstone_stairs', 'blackstone_wall', 'polished_blackstone_stairs', 'chiseled_polished_blackstone', 'polished_blackstone_bricks', 'polished_blackstone_brick_wall', 'polished_blackstone_brick_stairs', 'polished_blackstone', 'polished_blackstone_wall'],
    ['end_stone_bricks', 'end_stone_brick_stairs', 'end_stone_brick_wall', 'end_stone'],
    ['purpur_block', 'purpur_stairs', 'purpur_pillar'],
    ['quartz_block', 'quartz_stairs', 'quartz_pillar', 'quartz_bricks', 'chiseled_quartz_block'],
    ['smooth_quartz', 'smooth_quartz_stairs'],
    ['cut_copper', 'cut_copper_stairs'],
    ['exposed_cut_copper', 'exposed_cut_copper_stairs'],
    ['weathered_cut_copper', 'weathered_cut_copper_stairs'],
    ['oxidized_cut_copper', 'oxidized_cut_copper_stairs'],
    ['waxed_cut_copper', 'waxed_cut_copper_stairs'],
    ['waxed_exposed_cut_copper', 'waxed_exposed_cut_copper_stairs'],
    ['waxed_weathered_cut_copper', 'waxed_weathered_cut_copper_stairs'],
    ['waxed_oxidized_cut_copper', 'waxed_oxidized_cut_copper_stairs'],
];

// Exclude these recipes because they already exist in vanilla.
export const existingRecipes = [
    ['stone', 'stone_stairs'],
    ['stone', 'chiseled_stone_bricks'],
    ['stone', 'stone_brick_stairs'],
    ['stone', 'stone_bricks'],
    ['stone', 'stone_brick_wall'],
    ['cobblestone', 'cobblestone_wall'],
    ['cobblestone', 'cobblestone_stairs'],
    ['mossy_cobblestone', 'mossy_cobblestone_wall'],
    ['mossy_cobblestone', 'mossy_cobblestone_stairs'],
    ['stone_bricks', 'chiseled_stone_bricks'],
    ['stone_bricks', 'stone_brick_stairs'],
    ['stone_bricks', 'stone_brick_wall'],
    ['mossy_stone_bricks', 'mossy_stone_brick_stairs'],
    ['mossy_stone_bricks', 'mossy_stone_brick_wall'],
    ['granite', 'polished_granite'],
    ['granite', 'granite_wall'],
    ['granite', 'granite_stairs'],
    ['granite', 'polished_granite_stairs'],
    ['diorite', 'polished_diorite'],
    ['diorite', 'diorite_wall'],
    ['diorite', 'diorite_stairs'],
    ['diorite', 'polished_diorite_stairs'],
    ['andesite', 'polished_andesite'],
    ['andesite', 'andesite_wall'],
    ['andesite', 'andesite_stairs'],
    ['andesite', 'polished_andesite_stairs'],
    ['cobbled_deepslate', 'chiseled_deepslate'],
    ['cobbled_deepslate', 'cobbled_deepslate_stairs'],
    ['cobbled_deepslate', 'cobbled_deepslate_wall'],
    ['cobbled_deepslate', 'deepslate_brick_stairs'],
    ['cobbled_deepslate', 'deepslate_brick_wall'],
    ['cobbled_deepslate', 'deepslate_bricks'],
    ['cobbled_deepslate', 'deepslate_tile_stairs'],
    ['cobbled_deepslate', 'deepslate_tile_wall'],
    ['cobbled_deepslate', 'deepslate_tiles'],
    ['cobbled_deepslate', 'polished_deepslate'],
    ['cobbled_deepslate', 'polished_deepslate_stairs'],
    ['cobbled_deepslate', 'polished_deepslate_wall'],
    ['polished_deepslate', 'deepslate_brick_stairs'],
    ['polished_deepslate', 'deepslate_brick_wall'],
    ['polished_deepslate', 'deepslate_bricks'],
    ['polished_deepslate', 'deepslate_tile_stairs'],
    ['polished_deepslate', 'deepslate_tile_wall'],
    ['polished_deepslate', 'deepslate_tiles'],
    ['polished_deepslate', 'polished_deepslate_stairs'],
    ['polished_deepslate', 'polished_deepslate_wall'],
    ['deepslate_bricks', 'deepslate_brick_stairs'],
    ['deepslate_bricks', 'deepslate_brick_wall'],
    ['deepslate_bricks', 'deepslate_tile_stairs'],
    ['deepslate_bricks', 'deepslate_tile_wall'],
    ['deepslate_bricks', 'deepslate_tiles'],
    ['deepslate_tiles', 'deepslate_tile_stairs'],
    ['deepslate_tiles', 'deepslate_tile_wall'],
    ['bricks', 'brick_stairs'],
    ['bricks', 'brick_wall'],
    ['mud_bricks', 'mud_brick_stairs'],
    ['mud_bricks', 'mud_brick_wall'],
    ['sandstone', 'chiseled_sandstone'],
    ['sandstone', 'cut_sandstone'],
    ['sandstone', 'sandstone_stairs'],
    ['sandstone', 'sandstone_wall'],
    ['smooth_sandstone', 'smooth_sandstone_stairs'],
    ['red_sandstone', 'chiseled_red_sandstone'],
    ['red_sandstone', 'cut_red_sandstone'],
    ['red_sandstone', 'red_sandstone_stairs'],
    ['red_sandstone', 'red_sandstone_wall'],
    ['prismarine', 'prismarine_stairs'],
    ['prismarine', 'prismarine_wall'],
    ['prismarine_bricks', 'prismarine_brick_stairs'],
    ['dark_prismarine', 'dark_prismarine_stairs'],
    ['nether_bricks', 'chiseled_nether_bricks'],
    ['nether_bricks', 'nether_brick_stairs'],
    ['nether_bricks', 'nether_brick_wall'],
    ['red_nether_bricks', 'red_nether_brick_stairs'],
    ['red_nether_bricks', 'red_nether_brick_wall'],
    ['blackstone', 'blackstone_stairs'],
    ['blackstone', 'blackstone_wall'],
    ['blackstone', 'chiseled_polished_blackstone'],
    ['blackstone', 'polished_blackstone'],
    ['blackstone', 'polished_blackstone_brick_stairs'],
    ['blackstone', 'polished_blackstone_brick_wall'],
    ['blackstone', 'polished_blackstone_bricks'],
    ['blackstone', 'polished_blackstone_stairs'],
    ['blackstone', 'polished_blackstone_wall'],
    ['polished_blackstone', 'polished_blackstone_brick_stairs'],
    ['polished_blackstone', 'polished_blackstone_brick_wall'],
    ['polished_blackstone', 'polished_blackstone_bricks'],
    ['polished_blackstone', 'polished_blackstone_stairs'],
    ['polished_blackstone', 'polished_blackstone_wall'],
    ['polished_blackstone_bricks', 'polished_blackstone_brick_stairs'],
    ['polished_blackstone_bricks', 'polished_blackstone_brick_wall'],
    ['end_stone', 'end_stone_bricks'],
    ['end_stone', 'end_stone_brick_stairs'],
    ['end_stone', 'end_stone_brick_wall'],
    ['end_stone_bricks', 'end_stone_brick_stairs'],
    ['end_stone_bricks', 'end_stone_brick_wall'],
    ['purpur_block', 'purpur_pillar'],
    ['purpur_block', 'purpur_stairs'],
    ['quartz_block', 'chiseled_quartz_block'],
    ['quartz_block', 'quartz_bricks'],
    ['quartz_block', 'quartz_pillar'],
    ['quartz_block', 'quartz_stairs'],
    ['smooth_quartz', 'smooth_quartz_stairs'],
    ['cut_copper', 'cut_copper_stairs'],
    ['exposed_cut_copper', 'exposed_cut_copper_stairs'],
    ['weathered_cut_copper', 'weathered_cut_copper_stairs'],
    ['oxidized_cut_copper', 'oxidized_cut_copper_stairs'],
    ['waxed_cut_copper', 'waxed_cut_copper_stairs'],
    ['waxed_exposed_cut_copper', 'waxed_exposed_cut_copper_stairs'],
    ['waxed_weathered_cut_copper', 'waxed_weathered_cut_copper_stairs'],
    ['waxed_oxidized_cut_copper', 'waxed_oxidized_cut_copper_stairs'],
];
